spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: tochratana
    password: 1234
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/istad-outh2
  application:
    name: advanced-ecommerce-api
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file-upload:
  server-path: /Users/tochratana/Microservice/fileUpload/
#server:
#  port: 9090

