# Use "wildcard" to exprose all endpoint
# Can also expose individual endpoint with a comma-delimited list
spring.application.name=01-spring-boot-overview

# ? Expose specific endpoints (or use * to expose all for dev)
management.endpoints.web.exposure.include=*

# ? Enable info.env to appear in /actuator/info
management.info.env.enabled=true

# Exclude individual endpoint with a comma-delimited
# management.endpoints.web.exposure.exclude=health,info
info.app.name=My Supper CoolApp
info.app.description=A crazy fun app, yoohoo!
info.app.version=1.0.0

#
# Defind my crazy property
#
coach.name = A B
team.name = rml


#
# Change server port, defualt port 8080
#
server.port=7070 

#
# Set the context part of application
# All request should be prefix with /mycoolapp
server.servlet.context-path=/mycoolapp